<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Cryosoft.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Cryosoft
{
    global $Cryosoft__t_stSKBRParam;
    class stSKBRParam
    {
        public function __construct($lfControlTemp=0.0, $lfLoadingRateMax=0.0)
        {
            $this->lfControlTemp = $lfControlTemp;
            $this->lfLoadingRateMax = $lfLoadingRateMax;
        }

        public function __toString()
        {
            global $Cryosoft__t_stSKBRParam;
            return IcePHP_stringify($this, $Cryosoft__t_stSKBRParam);
        }

        public $lfControlTemp;
        public $lfLoadingRateMax;
    }

    $Cryosoft__t_stSKBRParam = IcePHP_defineStruct('::Cryosoft::stSKBRParam', '\\Cryosoft\\stSKBRParam', array(
        array('lfControlTemp', $IcePHP__t_double),
        array('lfLoadingRateMax', $IcePHP__t_double)));
}

namespace Cryosoft
{
    global $Cryosoft__t_stSKConf;
    class stSKConf
    {
        public function __construct($tcDSN='', $tcUID='', $tcPWD='', $tcTracePath='', $ldIdUser=0, $ldIdStudy=0, $ldIdTmp=0, $cConnectToDB=0, $cInitTrace=0)
        {
            $this->tcDSN = $tcDSN;
            $this->tcUID = $tcUID;
            $this->tcPWD = $tcPWD;
            $this->tcTracePath = $tcTracePath;
            $this->ldIdUser = $ldIdUser;
            $this->ldIdStudy = $ldIdStudy;
            $this->ldIdTmp = $ldIdTmp;
            $this->cConnectToDB = $cConnectToDB;
            $this->cInitTrace = $cInitTrace;
        }

        public function __toString()
        {
            global $Cryosoft__t_stSKConf;
            return IcePHP_stringify($this, $Cryosoft__t_stSKConf);
        }

        public $tcDSN;
        public $tcUID;
        public $tcPWD;
        public $tcTracePath;
        public $ldIdUser;
        public $ldIdStudy;
        public $ldIdTmp;
        public $cConnectToDB;
        public $cInitTrace;
    }

    $Cryosoft__t_stSKConf = IcePHP_defineStruct('::Cryosoft::stSKConf', '\\Cryosoft\\stSKConf', array(
        array('tcDSN', $IcePHP__t_string),
        array('tcUID', $IcePHP__t_string),
        array('tcPWD', $IcePHP__t_string),
        array('tcTracePath', $IcePHP__t_string),
        array('ldIdUser', $IcePHP__t_long),
        array('ldIdStudy', $IcePHP__t_long),
        array('ldIdTmp', $IcePHP__t_long),
        array('cConnectToDB', $IcePHP__t_byte),
        array('cInitTrace', $IcePHP__t_byte)));
}
?>
