<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `IBrainCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\BrainCalculator
{
    global $Cryosoft_BrainCalculator__t_IBrainCalculator;
    global $Cryosoft_BrainCalculator__t_IBrainCalculatorPrx;

    class IBrainCalculatorPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::BrainCalculator::IBrainCalculator', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::BrainCalculator::IBrainCalculator', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::BrainCalculator::IBrainCalculator';
        }
    }

    $Cryosoft_BrainCalculator__t_IBrainCalculator = IcePHP_defineClass('::Cryosoft::BrainCalculator::IBrainCalculator', '\\Cryosoft\\BrainCalculator\\IBrainCalculator', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_BrainCalculator__t_IBrainCalculatorPrx = IcePHP_defineProxy('::Cryosoft::BrainCalculator::IBrainCalculator', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_BrainCalculator__t_IBrainCalculatorPrx, 'BRTeachCalculation', 0, 0, 0, array(array($Cryosoft__t_stSKConf), array($Cryosoft__t_stSKBRParam), array($IcePHP__t_long)), null, array($IcePHP__t_long), null);
    IcePHP_defineOperation($Cryosoft_BrainCalculator__t_IBrainCalculatorPrx, 'shutdown', 0, 0, 0, null, null, null, null);
}
?>
