<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `IComponentBuilder.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\ComponentBuilder
{
    global $Cryosoft_ComponentBuilder__t_IComponentBuilder;
    global $Cryosoft_ComponentBuilder__t_IComponentBuilderPrx;

    class IComponentBuilderPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::ComponentBuilder::IComponentBuilder', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::ComponentBuilder::IComponentBuilder', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::ComponentBuilder::IComponentBuilder';
        }
    }

    $Cryosoft_ComponentBuilder__t_IComponentBuilder = IcePHP_defineClass('::Cryosoft::ComponentBuilder::IComponentBuilder', '\\Cryosoft\\ComponentBuilder\\IComponentBuilder', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_ComponentBuilder__t_IComponentBuilderPrx = IcePHP_defineProxy('::Cryosoft::ComponentBuilder::IComponentBuilder', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_ComponentBuilder__t_IComponentBuilderPrx, 'CBComponentCalculation', 0, 0, 0, array(array($Cryosoft__t_stSKConf)), null, array($IcePHP__t_long), null);
}
?>
