<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `IConsumptionCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\ConsumptionCalculator
{
    global $Cryosoft_ConsumptionCalculator__t_IConsumptionCalculator;
    global $Cryosoft_ConsumptionCalculator__t_IConsumptionCalculatorPrx;

    class IConsumptionCalculatorPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::ConsumptionCalculator::IConsumptionCalculator', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::ConsumptionCalculator::IConsumptionCalculator', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::ConsumptionCalculator::IConsumptionCalculator';
        }
    }

    $Cryosoft_ConsumptionCalculator__t_IConsumptionCalculator = IcePHP_defineClass('::Cryosoft::ConsumptionCalculator::IConsumptionCalculator', '\\Cryosoft\\ConsumptionCalculator\\IConsumptionCalculator', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_ConsumptionCalculator__t_IConsumptionCalculatorPrx = IcePHP_defineProxy('::Cryosoft::ConsumptionCalculator::IConsumptionCalculator', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_ConsumptionCalculator__t_IConsumptionCalculatorPrx, 'COCConsumptionCalculation', 0, 0, 0, array(array($Cryosoft__t_stSKConf)), null, array($IcePHP__t_long), null);
}
?>
