<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `ICryoRunning.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\CryoRunning
{
    global $Cryosoft_CryoRunning__t_ICryoRunning;
    global $Cryosoft_CryoRunning__t_ICryoRunningPrx;

    class ICryoRunningPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::CryoRunning::ICryoRunning', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::CryoRunning::ICryoRunning', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::CryoRunning::ICryoRunning';
        }
    }

    $Cryosoft_CryoRunning__t_ICryoRunning = IcePHP_defineClass('::Cryosoft::CryoRunning::ICryoRunning', '\\Cryosoft\\CryoRunning\\ICryoRunning', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_CryoRunning__t_ICryoRunningPrx = IcePHP_defineProxy('::Cryosoft::CryoRunning::ICryoRunning', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_CryoRunning__t_ICryoRunningPrx, 'CRRSetStatus', 0, 0, 0, array(array($IcePHP__t_long), array($IcePHP__t_long)), null, array($IcePHP__t_long), null);
    IcePHP_defineOperation($Cryosoft_CryoRunning__t_ICryoRunningPrx, 'CRRGetStatus', 0, 0, 0, array(array($IcePHP__t_long), array($IcePHP__t_long)), null, array($IcePHP__t_long), null);
    IcePHP_defineOperation($Cryosoft_CryoRunning__t_ICryoRunningPrx, 'CRRNextStatus', 0, 0, 0, array(array($IcePHP__t_long)), null, array($IcePHP__t_long), null);
}
?>
