<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `IDimMatCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\DimMatCalculator
{
    global $Cryosoft_DimMatCalculator__t_IDimMatCalculator;
    global $Cryosoft_DimMatCalculator__t_IDimMatCalculatorPrx;

    class IDimMatCalculatorPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::DimMatCalculator::IDimMatCalculator', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::DimMatCalculator::IDimMatCalculator', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::DimMatCalculator::IDimMatCalculator';
        }
    }

    $Cryosoft_DimMatCalculator__t_IDimMatCalculator = IcePHP_defineClass('::Cryosoft::DimMatCalculator::IDimMatCalculator', '\\Cryosoft\\DimMatCalculator\\IDimMatCalculator', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_DimMatCalculator__t_IDimMatCalculatorPrx = IcePHP_defineProxy('::Cryosoft::DimMatCalculator::IDimMatCalculator', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_DimMatCalculator__t_IDimMatCalculatorPrx, 'DMCCalculation', 0, 0, 0, array(array($Cryosoft__t_stSKConf), array($IcePHP__t_int)), null, array($IcePHP__t_long), null);
}
?>
