<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `IEquipmentBuilder.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\EquipmentBuilder
{
    global $Cryosoft_EquipmentBuilder__t_IEquipmentBuilder;
    global $Cryosoft_EquipmentBuilder__t_IEquipmentBuilderPrx;

    class IEquipmentBuilderPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::EquipmentBuilder::IEquipmentBuilder', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::EquipmentBuilder::IEquipmentBuilder', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::EquipmentBuilder::IEquipmentBuilder';
        }
    }

    $Cryosoft_EquipmentBuilder__t_IEquipmentBuilder = IcePHP_defineClass('::Cryosoft::EquipmentBuilder::IEquipmentBuilder', '\\Cryosoft\\EquipmentBuilder\\IEquipmentBuilder', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_EquipmentBuilder__t_IEquipmentBuilderPrx = IcePHP_defineProxy('::Cryosoft::EquipmentBuilder::IEquipmentBuilder', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_EquipmentBuilder__t_IEquipmentBuilderPrx, 'EBEquipmentCalculation', 0, 0, 0, array(array($Cryosoft__t_stSKConf)), null, array($IcePHP__t_long), null);
}
?>
