<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `IInitTemperature.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\InitTemperature
{
    global $Cryosoft_InitTemperature__t_IInitTemperature;
    global $Cryosoft_InitTemperature__t_IInitTemperaturePrx;

    class IInitTemperaturePrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::InitTemperature::IInitTemperature', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::InitTemperature::IInitTemperature', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::InitTemperature::IInitTemperature';
        }
    }

    $Cryosoft_InitTemperature__t_IInitTemperature = IcePHP_defineClass('::Cryosoft::InitTemperature::IInitTemperature', '\\Cryosoft\\InitTemperature\\IInitTemperature', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_InitTemperature__t_IInitTemperaturePrx = IcePHP_defineProxy('::Cryosoft::InitTemperature::IInitTemperature', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_InitTemperature__t_IInitTemperaturePrx, 'ITInitTemperature', 0, 0, 0, array(array($Cryosoft__t_stSKConf)), null, array($IcePHP__t_long), null);
}
?>
