<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `IKernelToolCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\KernelToolCalculator
{
    global $Cryosoft_KernelToolCalculator__t_IKernelToolCalculator;
    global $Cryosoft_KernelToolCalculator__t_IKernelToolCalculatorPrx;

    class IKernelToolCalculatorPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::KernelToolCalculator::IKernelToolCalculator', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::KernelToolCalculator::IKernelToolCalculator', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::KernelToolCalculator::IKernelToolCalculator';
        }
    }

    $Cryosoft_KernelToolCalculator__t_IKernelToolCalculator = IcePHP_defineClass('::Cryosoft::KernelToolCalculator::IKernelToolCalculator', '\\Cryosoft\\KernelToolCalculator\\IKernelToolCalculator', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_KernelToolCalculator__t_IKernelToolCalculatorPrx = IcePHP_defineProxy('::Cryosoft::KernelToolCalculator::IKernelToolCalculator', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_KernelToolCalculator__t_IKernelToolCalculatorPrx, 'KTCalculator', 0, 0, 0, array(array($Cryosoft__t_stSKConf), array($IcePHP__t_int)), null, array($IcePHP__t_long), null);
    IcePHP_defineOperation($Cryosoft_KernelToolCalculator__t_IKernelToolCalculatorPrx, 'KTSECgetLocalName', 0, 0, 0, array(array($IcePHP__t_int)), null, array($IcePHP__t_string), null);
    IcePHP_defineOperation($Cryosoft_KernelToolCalculator__t_IKernelToolCalculatorPrx, 'GetLocalMachineIdentifier', 0, 0, 0, null, null, array($IcePHP__t_string), null);
}
?>
