<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `ILayoutCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\LayoutCalculator
{
    global $Cryosoft_LayoutCalculator__t_ILayoutCalculator;
    global $Cryosoft_LayoutCalculator__t_ILayoutCalculatorPrx;

    class ILayoutCalculatorPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::LayoutCalculator::ILayoutCalculator', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::LayoutCalculator::ILayoutCalculator', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::LayoutCalculator::ILayoutCalculator';
        }
    }

    $Cryosoft_LayoutCalculator__t_ILayoutCalculator = IcePHP_defineClass('::Cryosoft::LayoutCalculator::ILayoutCalculator', '\\Cryosoft\\LayoutCalculator\\ILayoutCalculator', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_LayoutCalculator__t_ILayoutCalculatorPrx = IcePHP_defineProxy('::Cryosoft::LayoutCalculator::ILayoutCalculator', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_LayoutCalculator__t_ILayoutCalculatorPrx, 'LCCalculation', 0, 0, 0, array(array($Cryosoft__t_stSKConf), array($IcePHP__t_int)), null, array($IcePHP__t_double), null);
}
?>
