<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `IPipelineCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\PipelineCalculator
{
    global $Cryosoft_PipelineCalculator__t_IPipelineCalculator;
    global $Cryosoft_PipelineCalculator__t_IPipelineCalculatorPrx;

    class IPipelineCalculatorPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::PipelineCalculator::IPipelineCalculator', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::PipelineCalculator::IPipelineCalculator', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::PipelineCalculator::IPipelineCalculator';
        }
    }

    $Cryosoft_PipelineCalculator__t_IPipelineCalculator = IcePHP_defineClass('::Cryosoft::PipelineCalculator::IPipelineCalculator', '\\Cryosoft\\PipelineCalculator\\IPipelineCalculator', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_PipelineCalculator__t_IPipelineCalculatorPrx = IcePHP_defineProxy('::Cryosoft::PipelineCalculator::IPipelineCalculator', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_PipelineCalculator__t_IPipelineCalculatorPrx, 'PCPipelineCalculation', 0, 0, 0, array(array($Cryosoft__t_stSKConf)), null, array($IcePHP__t_long), null);
}
?>
