<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `IWeightCalculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Cryosoft.php';
}

namespace Cryosoft\WeightCalculator
{
    global $Cryosoft_WeightCalculator__t_IWeightCalculator;
    global $Cryosoft_WeightCalculator__t_IWeightCalculatorPrx;

    class IWeightCalculatorPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Cryosoft::WeightCalculator::IWeightCalculator', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Cryosoft::WeightCalculator::IWeightCalculator', $facet);
        }

        public static function ice_staticId()
        {
            return '::Cryosoft::WeightCalculator::IWeightCalculator';
        }
    }

    $Cryosoft_WeightCalculator__t_IWeightCalculator = IcePHP_defineClass('::Cryosoft::WeightCalculator::IWeightCalculator', '\\Cryosoft\\WeightCalculator\\IWeightCalculator', -1, false, true, $Ice__t_Value, null);

    $Cryosoft_WeightCalculator__t_IWeightCalculatorPrx = IcePHP_defineProxy('::Cryosoft::WeightCalculator::IWeightCalculator', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Cryosoft_WeightCalculator__t_IWeightCalculatorPrx, 'WCWeightCalculation', 0, 0, 0, array(array($Cryosoft__t_stSKConf), array($IcePHP__t_int)), null, array($IcePHP__t_long), null);
}
?>
